Code/nathan/django/tester/products/urls.py
from django.urls import path

from . import views

app_name = 'products'

urlpatterns = [
    path('home/', views.home_view, name='home'),
    path('products/', views.products_view, name='product'),
    path('contact/', views.contact_view, name='contact'),
    # path('cart/', views.cart_view, name='cart'),
]

Code/nathan/django/tester/tester/urls.py
from django.contrib import admin
from django.contrib.auth import views
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
# from ..users.views import register_view
import os
os.sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
from users.views import register_view


urlpatterns = [
    path('', include('products.urls')),
    path('admin/', admin.site.urls),
    path('register/', register_view, name='register'),
    path('login/', views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Code/nathan/django/tester/products/models.py
from django.db import models


#
# class Cart(models.Model):
#     title       = models.CharField(max_length=120)
#     description = models.TextField(blank=True, null=True)
#     price       = models.DecimalField(decimal_places=2, max_digits=10000)
#     featured    = models.BooleanField()

class Product(models.Model):
    title = models.CharField(max_length=120)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(decimal_places=2, max_digits=10000)
    featured = models.BooleanField()
    # in_cart = models.BooleanField()
    # cart = models.ForeignKey(Cart, on_delete=models.CASCADE)

Code/nathan/django/tester/users/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm


class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()


    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

Code/nathan/django/tester/products/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .models import Product

# Create your views here.
def home_view(request):

    my_context = {
        'title': "has good deals",
        'my_number': 123,
        'my_list': ['Plush Toys', 'Posters', 'Clothes', 'MP3\'s', 'Foreign Candy'],
        'my_html': "<h3>sells lots of things</h3>"
    }
    return render(request, "products/home.html", my_context)


def contact_view(request):

    return render(request, "products/contact.html", {})


def products_view(request):
    products = Product.objects.all()
    context = {'products': products}
    return render(request, "products/detail.html", context)

#
# def cart_view(request):
#
#     return render(request, "products/cart.html", {})
# <nav>
#     <a href="{% url 'users:login' %}">Login</a>
#     <a href="{% url 'users:logout' %}">Logout</a>
#     <a href="{% url 'users:register' %}">Register</a>
# </nav>

Code/nathan/django/tester/users/views.py
from django.shortcuts import render, redirect
from django.contrib import messages
from django.urls import reverse
from .forms import UserRegisterForm


def register_view(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account Created for {username}!')
            return redirect(reverse('login'))
    else:
        form = UserRegisterForm()
    return render(request, 'users/registration.html', {'form': form})

# messages.debug
# messages.info
# messages.success
# messages.warning
# messages.error

Code/nathan/django/tester/products/templates/products/base.html
{% load static %}
<html>
    <head>
        <title>Hi</title>
        <link rel="stylesheet" type="text/css" href="{% static 'products/css/main.css' %}">
    </head>
<body>
    {% include 'products/nav.html' %}
    {% if messages %}
        {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
            {{ message }}
            </div>
        {% endfor %}
    {% endif %}
    {% block content %}
    {% endblock %}
</body>
</html>

Code/nathan/django/tester/products/templates/products/cart.html
{% extends 'products/base.html' %}

{% block content %}
{% for object in cart_objects %}
<h2>{{ object.title }}</h2>
<p>{% if object.description != None and object.description != '' %}{{ object.description }}{% else %}Coming Soon{% endif %}</p>
<p>{{ object.price }}</p>
<hr>
{% endfor %}
{% endblock %}

Code/nathan/django/tester/products/templates/products/contact.html
{% extends 'products/base.html' %}

{% block content %}
    <h1>Have Questions?</h1>
    <p>Contact Us @ 555-555-5555</p>
{% endblock %}

Code/nathan/django/tester/products/templates/products/detail.html
{% extends 'products/base.html' %}

{% block content %}
{% for product in products %}
    <h2>{{ product.title }}</h2>
    <p>{% if product.description != None and product.description != '' %}{{ product.description }}{% else %}Coming Soon{% endif %}</p>
    <p>{{ product.price }}</p>
    <hr>
{% endfor %}
{% endblock %}

Code/nathan/django/tester/products/templates/products/home.html
{% extends 'products/base.html' %}

{% block content %}
        <h1>is a great web-store: welcome {{ request.user }}!</h1>
        <p>says: Hey there planet</p>
        <h2>{{ title|capfirst|title }}</h2>
        <h4>{{ my_html|safe }}</h4>

    <!--<p>-->
        <!--{{ my_text }}, {{ my_number }}-->
        <!--{{ my_list }}-->
    <!--</p>-->

    <ul>
    {% for my_item in my_list %}

        {% if my_item == 5 %}
        <li>{{ forloop.counter }} - {{ my_item }}</li>

        {% else %}
        <li>{{ forloop.counter }} - {{ my_item }}</li>
        {% endif %}

    {% endfor %}
    </ul>

{% endblock %}

Code/nathan/django/tester/products/templates/products/nav.html
<nav>
    <a href="{% url 'products:home' %}">Home</a>
    <a href="{% url 'products:product' %}">Products</a>
    <a href="{% url 'products:contact' %}">contact</a>
</nav>

Code/nathan/django/tester/products/templates/products/posh.html
{% extends 'products/base.html' %}

{% block content %}
    <h1>posh uwu</h1>
    {{ request.user }}
    <p>I am Template</p>
{% endblock %}

Code/nathan/django/tester/products/templates/products/product_create.html
{% extends 'products/base.html' %}

{% block content %}
<form>
{{ form.as_p }}
<input type='submit' value='save' />
</form>
{% endblock %}