Code/Richard/django/mentcom/forum/urls.py
from django.urls import path
from . import views

app_name = 'forum'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login_template, name='login'),
    path('register_user/', views.register_user, name='register_user'),
    path('login_user/', views.login_user, name='login_user'),
    path('savepost/', views.savepost, name='savepost'),
    path('logout/', views.logout_user, name='logout'),
    path('edit_post/', views.edit_post, name='edit_post'),
    path('delete_post/', views.delete_post, name="delete_post"),
    path('test_recursion/', views.test_recursion, name='test_recursion')
    
]

Code/Richard/django/mentcom/mentcom/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('forum.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

Code/Richard/django/mentcom/forum/models.py
from django.db import models

# Create your models here.

from django.contrib.auth.models import User

class Topic(models.Model):
    title = models.CharField(max_length=1000)
    url = models.CharField(max_length=500)
    byline = models.CharField(max_length=200)
    published_date = models.DateField()
    abstract = models.CharField(max_length=2500)

    def __str__(self):
        return self.title
    
    def get_top_level_posts(self):
        return self.posts.filter(parent__isnull=True)

class Post(models.Model):
    author = models.ForeignKey(User, on_delete=models.PROTECT)
    date = models.DateField(auto_now_add=True)
    text = models.TextField(max_length=10000)
    topic = models.ForeignKey(Topic, on_delete=models.PROTECT, related_name='posts')
    parent = models.ForeignKey('self', null=True, blank=True, default=None, on_delete=models.PROTECT, related_name='children')

    def __str__(self):
        return self.text

Code/Richard/django/mentcom/forum/views.py
from django.shortcuts import render, get_object_or_404
from .models import Topic, User, Post
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    topics = Topic.objects.order_by('-published_date')
    context = {
        'topics' : topics
    }
    return render(request, 'forum/index.html', context)


def login_template(request):
    return render(request, 'forum/login.html', {})


def savepost(request):
    post_data = request.POST['post_text']
    topic_id = request.POST['topic_id']
    if 'post_id' in request.POST:
        post_id = request.POST['post_id']
    else:
        post_id = None
    post = Post(text=post_data, author=request.user, topic_id=topic_id, parent_id=post_id)
    post.save()
    return HttpResponseRedirect(reverse('forum:index'))

def edit_post(request):
    post_data = request.POST['edit_text']
    post_id = request.POST['post_id']
    post = get_object_or_404(Post, pk=post_id)
    post.text = post_data
    post.save()
    return HttpResponseRedirect(reverse('forum:index'))

def delete_post(request):
    post_id = request.POST["post_id"]
    post = get_object_or_404(Post, pk=post_id)
    post.text = "This comment has been deleted by its author."
    post.save()
    return HttpResponseRedirect(reverse('forum:index'))

def register_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    next = request.POST['next']

    if password != confirm_password:
        return HttpResponseRedirect(reverse('forum:index'))

    user = User.objects.create_user(username, email, password)
    login(request, user)

    if next == '':
        return HttpResponseRedirect(reverse('forum:index'))
    return HttpResponseRedirect(next)

def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    next = request.POST['next']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next == '':
            return HttpResponseRedirect(reverse('forum:index'))
        return HttpResponseRedirect(next)
    return HttpResponseRedirect(reverse('forum:index'))

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('forum:index'))


def post_to_html(post, depth):
    r = '\t'*depth + post.text + '\n'
    for child in post.children.order_by('date'):
        r += post_to_html(child, depth+1)
    return r

def test_recursion(request):
    output = '<pre>'
    topics = Topic.objects.order_by('published_date')
    for topic in topics:
        output += topic.title + '\n'
        posts = topic.posts.filter(parent__isnull=True)
        for post in posts:
            output += post_to_html(post, 1)
    return HttpResponse(output + '</pre>')

Code/Richard/django/mentcom/mentcom/forum/views.py
from django.shortcuts import render, get_object_or_404
from .models import Topic, User, Post
from django.shortcuts import render, reverse
from django.http import HttpResponse, HttpResponseRedirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login, logout

# Create your views here.

def index(request):
    topics = Topic.objects.order_by('-published_date')
    context = {
        'topics' : topics
    }
    return render(request, 'forum/index.html', context)


def login_template(request):
    return render(request, 'forum/login.html', {})


def savepost(request):
    post_data = request.POST['post_text']
    topic_id = request.POST['topic_id']
    if 'post_id' in request.POST:
        post_id = request.POST['post_id']
    else:
        post_id = None
    post = Post(text=post_data, author=request.user, topic_id=topic_id, parent_id=post_id)
    post.save()
    return HttpResponseRedirect(reverse('forum:index'))

def edit_post(request):
    post_data = request.POST['edit_text']
    post_id = request.POST['post_id']
    post = get_object_or_404(Post, pk=post_id)
    post.text = post_data
    post.save()
    return HttpResponseRedirect(reverse('forum:index'))

def delete_post(request):
    post_id = request.POST["post_id"]
    post = get_object_or_404(Post, pk=post_id)
    post.text = "<i>This comment has been deleted by its author.</i>"
    post.save()
    return HttpResponseRedirect(reverse('forum:index'))

def register_user(request):
    username = request.POST['username']
    email = request.POST['email']
    password = request.POST['password']
    confirm_password = request.POST['confirm_password']
    next = request.POST['next']

    if password != confirm_password:
        return HttpResponseRedirect(reverse('forum:index'))

    user = User.objects.create_user(username, email, password)
    login(request, user)

    if next == '':
        return HttpResponseRedirect(reverse('forum:index'))
    return HttpResponseRedirect(next)

def login_user(request):
    username = request.POST['username']
    password = request.POST['password']
    next = request.POST['next']
    user = authenticate(request, username=username, password=password)
    if user is not None:
        login(request, user)
        if next == '':
            return HttpResponseRedirect(reverse('forum:index'))
        return HttpResponseRedirect(next)
    return HttpResponseRedirect(reverse('forum:index'))

def logout_user(request):
    logout(request)
    return HttpResponseRedirect(reverse('forum:index'))


def post_to_html(post, depth):
    r = '\t'*depth + post.text + '\n'
    for child in post.children.order_by('date'):
        r += post_to_html(child, depth+1)
    return r

def test_recursion(request):
    output = '<pre>'
    topics = Topic.objects.order_by('published_date')
    for topic in topics:
        output += topic.title + '\n'
        posts = topic.posts.filter(parent__isnull=True)
        for post in posts:
            output += post_to_html(post, 1)
    return HttpResponse(output + '</pre>')

Code/Richard/django/mentcom/forum/templates/forum/index.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
        <style>
            body {
                padding: 20px;
                padding-top: 90px;
            }
            .comments {
                background-color: lightgray;
                padding-bottom: 15px;
                margin-right:30px;
            }
            .pad_left_15 {
                padding-left: 15px;
            }
            .margin_bottom {
                margin-bottom: 5px;
            }
            .topic_title {
                font-weight: bold;
            }
            #topic_entry {
                padding-bottom: 5px;
            }
            .navbar {
                justify-content: space-around;
                margin-bottom: 20px;
            }
            .nav-item {
                color: white;
            }
            .comment_div {
                display: none;
                padding-left: 25px;
            }
            .comments {
                padding-top: 10px;
                font-style: italic;
            }
            .bold {
                font-weight: bold;
            }
            .no_bullet {
                list-style-type: none;
            }
            .flex-row {
                display: flex;
                flex-direction: row;
            }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark fixed-top">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href="{% url 'forum:index' %}">MentCom forum - The most-read articles from the New York Times</a>
                </div>
                <ul class="navbar-nav">
                    {% if not user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'forum:login' %}">Login or register to post a comment</a>
                    </li>
                    {% else%}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'forum:logout' %}">Logout</a>
                    </li>
                    {% endif %}
                </ul>
        </nav>
        <div id='"topic"'>
            {% if topics %}
                {% for topic in topics %}
                    <div id="topic_entry">
                        <h4>{{ topic.title }}</h4>  
                        <div class="small"><a href={{ topic.url }}>{{ topic.url }}</a> </div>
                        <div class="small"> {{ topic.byline }} </div>
                        <div class="small"> {{ topic.published_date }} </div>
                        <div class="small bold"> {{ topic.abstract }} </div>
                        <hr/>
                    </div>   

                    {% if user.is_authenticated %}
                    <button class="new_comment_bt small margin_bottom">Click to comment (please read article before commenting)</button>
                    <div  style="display:none">
                        <form action="{% url 'forum:savepost' %}" method="post">
                        {% csrf_token %}
                        <input type="hidden" name="topic_id" value="{{topic.id}}"/>
                        <textarea class="form-control rounded-0"  type="text" name="post_text" title="Post a comment here"></textarea>
                        <button type="submit" class="small">Submit comment</button>
                        </form>
                    </div>
                    {% endif %}

                    {% if topic.posts.all %}
                    <h6>Comments:</h6>
                    <button class="hide_comments_bt small">Hide Comments</button>

                        <ul>
                            {%for post in topic.get_top_level_posts %} 
                                {%include "forum/tree_template.html" %}
                            {%endfor%}
                        </ul>
                    
                    {% endif %}
                    <hr/><hr/>
                {% endfor %}
            {% endif %}
        </div>
        
        <script>
        $(".new_comment_bt").click(function() {
            $(this).hide().next().show()
        })
        
        $(".create_comment_bt").click(function() {
            $(this).hide()
            $('#comment_div_' + $(this).data('id')).show()
        })

        $(".edit_comment_bt").click(function() {
            $(this).hide()
            $('#edit_div_' + $(this).data('id')).show()
        })

        $(".hide_comments_bt").click(function() {
            if ($(this).text()==="Show Comments") {
                $(this).text("Hide Comments")
                .next().show()
            } else {
            $(this).text("Show Comments")
                .next().hide()
            }
            })

    </script>
    </body>
</html>

Code/Richard/django/mentcom/forum/templates/forum/login.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css">
        <style>
        body {
            padding: 20px;
        }
        #topic_title {
            font-style: bold;
        }
        #topic_entry {
            padding-bottom: 5px;
        }
        .navbar {
            justify-content: center;
        }
        </style>
    </head>
    <body>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">
            <div class="container-fluid">
                <div class="navbar-header">
                    <a class="navbar-brand" href=#>Forum registration page</a>
                </div>
                <ul class="navbar-nav">
                        <li class="nav-item">
                          <a class="nav-link" href="#">Login or register to post a comment</a>
                        </li>
                </ul>
        </nav>
        <h3>Already registered? Login:</h3>
        <form action="{% url 'forum:login_user' %}" method="post">
            {% csrf_token %}
            <input type="hidden" name="next" value="{{next}}"/>
            <input type="text" name="username" required placeholder="username"/>
            <input type="password" name="password" required placeholder="password"/>
            <button type="submit">login</button>
        </form>

        <h3>Not registered? Register here:</h3>
        <form action="{% url 'forum:register_user' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="next" value="{{next}}"/>
                <input type="text" name="username" required placeholder="username"/>
                <input type="text" name="email" required placeholder="email address"/>
                <input type="password" id="input_password" name="password" required placeholder="password"/>
                <input type="password" id="input_password_confirm" name="confirm_password" required placeholder="confirm password"/>
                <button id="bt_submit" type="submit">register</button>
            </form>
        </body>
    </html>

Code/Richard/django/mentcom/forum/templates/forum/tree_template.html
<li>
    <div class="comments">    
        <div class="small pad_left_15">{{post.text}}</div>
        <div class="small pad_left_15">{{post.author}}</div>
        <div class="small pad_left_15">{{post.date}}</div>
    </div>
    
    <div class="flex-row">
        {% if user.is_authenticated %}
            <button class="create_comment_bt small"  title="Add comment" data-id="{{post.id}}">&#43;</button>
        {% endif %}
    
        {% if post.author == user %}
            <button class="edit_comment_bt small"  title="Edit comment" data-id="{{post.id}}">&#9998;</button> 

            <form action="{% url 'forum:delete_post' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}"/>
                <button class="delete_comment small"  title="Delete comment" style="display:flex" type="submit">&#10007;</button>
            </form>
        {% endif %}
    </div>
    <div>
        <div id="comment_div_{{post.id}}" class="comment_div"> 
            <form action="{% url 'forum:savepost' %}" method="post">
                {% csrf_token %}
                <input type="hidden" name="post_id" value="{{post.id}}"/>
                <input type="hidden" name="topic_id" value="{{topic.id}}"/>
                <textarea class="form-control rounded-0" type="text" name="post_text" title="Post a comment here"></textarea>
                <button type="submit" class="small">Submit comment</button>
            </form>
        </div>

        <div id="edit_div_{{post.id}}" style="display:none">
            <form action="{% url 'forum:edit_post' %}" method="post">
                {% csrf_token %}
            <input type="hidden" name="post_id" value="{{post.id}}"/>
            <textarea class="form-control rounded-0 " style="margin-left:25px" type="text" name="edit_text">{{ post.text }}</textarea>
            <button class="submit_edit_bt small" style="display:flex" type="submit">Submit Edit</button>
            </form>
        </div>
    </div>

    {% if post.children.all %}
        <ul>
         {% for child in post.children.all %}
              {% with post=child template_name="forum/tree_template.html" %}
                   {% include template_name %}
              {% endwith %}
         {% endfor %}
         </ul>
    {% endif %}
</li>